### PR TITLE
[Bugfix] Draw: import KML does not draw anythings if xml headers

### LINKED ISSUE #2015: Draw: import KML does not draw anythings
### Steps to reproduce the issue

1. Go to https://demo.lizmap.com/lizmap_3_4/index.php/view/map/?repository=demo&project=qgis_info
2. Click on 'Draw'
3. Click on 'Import in GeoJSON, GPX, KML' and choose a KML file [kmls.zip](https://github.com/3liz/lizmap-web-client/files/5775147/kmls.zip)
4. The file name is well displayed but nothing on the map and the buttons are still deactivated

### Expected behavior
Display the KML content at the right place

### Screenshots and logs
No logs in the browser console

### Environment

 - Lizmap version: 3.4.0
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Ubuntu Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

### PR DESCRIPTION
**Pull request by rldhont**
If the KML file contain the xml header, it was not parsed.

Fixes #2015

### CODE REVIEW

**Comment by drillinP** [comment]
In the import function, there is a parameter called `file`. With this parameter we can get the file name and get the file extension.

**Comment by nboisteault** [comment]
@drillinP Please make one commit for linting and another for your fix. It is easier to read.

**Comment by drillinP** [comment]
@nboisteault It's done, in fact it's just that my vscode formats the code automatically when I save the file

**Review by drillinP — APPROVED** [review]
Good for me

**Comment by rldhont** [comment]
@drillinP peux-tu créer 2 fichiers KML pour les tests :+1: 

1. Sans l'en-tête xml
2. Avec l'en-tête xml

File: assets/src/modules/Digitizing.js [hunk 1]
```diff
@@ -472,19 +472,23 @@ export default class Digitizing {
...
         reader.onload = (() => {
             return (e) => {
                 const fileContent = e.target.result;
                 let OL6features;
 
                 // Handle GeoJSON, GPX or KML strings
                 try {
-                    if (fileContent[0] === '{') {
+                    // Check extension to the feature type
+                    if (fileExtension === 'geojson') {
```
Comment (rldhont) [inline assets/src/modules/Digitizing.js:486]: What if the extenion is json ?

File: .vscode/settings.json [hunk 2]
```diff
@@ -0,0 +1,3 @@
+{
+    "editor.formatOnSave": true
```
Comment (Gustry) [inline .vscode/settings.json:2]: Should we commit vscode user settings ?

File: assets/src/modules/Digitizing.js (hunk 1 above)
Comment (drillinP) [reply assets/src/modules/Digitizing.js:486]: I can make `if (fileExtension === 'geojson' || fileExtension === 'json')` ?

File: .vscode/settings.json (hunk 2 above)
Comment (nboisteault) [reply .vscode/settings.json:2]: No, we should not. Please @drillinP  ignore this file by editing `.git/info/exclude` and adding this file.

File: assets/src/modules/Digitizing.js (hunk 1 above)
Comment (rldhont) [reply assets/src/modules/Digitizing.js:486]: @drillinP I'll do it

File: .vscode/settings.json (hunk 2 above)
Comment (rldhont) [reply .vscode/settings.json:2]: @nboisteault @drillinP I'll do it

Comment (Gustry) [reply .vscode/settings.json:2]: Why `.git/info/exclude` and not just adding it in the `.gitignore`  in the repository? (the `.vscode` directory) ?

Comment (nboisteault) [reply .vscode/settings.json]: Yes we can do it this way but in this case we'll have to handle every files/directories created by different IDE, tools, etc.
As vscode is very popular, let's add this directory. It will avoid this directory to be committed by potential contributors in future.

Comment (rldhont) [reply .vscode/settings.json]: Done in `.gitignore`

File: assets/src/modules/Digitizing.js (hunk 1 above)
Comment (rldhont) [reply assets/src/modules/Digitizing.js]: Done

File: assets/src/modules/Digitizing.js [hunk 3]
```diff
@@ -469,29 +469,33 @@ export default class Digitizing {
         setTimeout(function () { URL.revokeObjectURL(a.href); }, 1500);
     }
 
-    import(file){
+    import(file) {
         const reader = new FileReader();
 
+        // Get extension file
+        var fileExtension = file.name.split('.').pop();
```
Comment (nboisteault) [inline assets/src/modules/Digitizing.js:476]: Please use avoid `var`. Use `let` or `const`. Here `const` is right.

File: tests/qgis-projects/tests/qgis_info.qgs [hunk 4]
```diff
@@ -0,0 +1,201 @@
+<qgis projectname="" version="3.10.13-A Coruña">
```
Comment (nboisteault) [inline tests/qgis-projects/tests/qgis_info.qgs:1]: @drillinP could you change file names. `qgis_info` doesn't tell what those files permit to test.

**Review by nboisteault — CHANGES_REQUESTED** [review]
