### PR TITLE
Fix: sandbox all iframes except those from the same origin

### LINKED ISSUE #4863: [Bug]: popup - iframe stop working on LWC 3.8
### What is the bug? (in English)

LWC 3.7.11
popup shows iframe in second table
imagem

LWC 3.8.3-pre
popup doesn´t show iframe in second table
imagem

LWC 3.7.11 and LWV 3.8.3-pre
data - everything works fine
imagem

### Steps to reproduce the issue

try beteween these versions

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.3-pre.7994
* Lizmap plugin : 4.4.2
* QGIS Desktop : 3.34.11
* QGIS Server : 3.34.11
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.11.0
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of Lizmap Web Client modules :</summary>
<br/>
* multiauth : 1.2.2
</details>

<details>
<summary>List of safeguards :</summary>
<br/>
* Mode : normal
* Allow parent folder : no
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

131.0.2

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by nboisteault**
Ticket : fix #4863

Funded by Valabre

### CODE REVIEW

File: assets/src/modules/Utils.js [hunk 1]
```diff
@@ -210,7 +210,9 @@ export default class Utils {
 
     static sanitizeGFIContent(content) {
         DOMPurify.addHook('afterSanitizeAttributes', node => {
-            if (node.nodeName === 'IFRAME') {
+            // Sandbox all iframes except those from the same origin
+            if (node.nodeName === 'IFRAME'
+                && !node.attributes['src'].textContent.startsWith(document.location.origin)) {
```
Comment (rldhont) [inline assets/src/modules/Utils.js:215]:
```suggestion
            if (node.nodeName === 'IFRAME' &&
                !node.attributes['src'].textContent.startsWith(document.location.origin)) {
```
Lint

**Review by rldhont — CHANGES_REQUESTED** [review]

**Comment by Gustry** [comment]
Is-it possible to have a quick E2E tests in `tests/end2end/playwright/xss.spec.js` and/or with #5260 ?

CF Paid support 3155

**Comment by Gustry** [comment]
Having a E2E tests allows us to have a project to check and show on https://sandbox.lizmap.com/lizmap_3_8/

**Review by Gustry — APPROVED** [review]

**Comment by nboisteault** [comment]
Manual backport to release_3_8
