### PR TITLE
Fix bug WFS layers not in attribute table

### LINKED ISSUE #1125: selection tool - special (accentuated) characters
hi

selection tool not taking layers from qgis whose name contains special characters

thanks

### PR DESCRIPTION
**Pull request by nboisteault**
Fix #1125 and probably a bug when users activate WFS for a layer and don't use it in attribute table.

### CODE REVIEW

File: lizmap/www/js/attributeTable.js [hunk 1]
```diff
@@ -3147,12 +3148,23 @@ var lizAttributeTable = function() {
...
+        }
     });
 
+    // We put selection layers which are also set in attribute table tool first then others
     for (var i = 0; i < selectionLayersSorted.length; i++) {
         options += selectionLayersSorted[i];
     }
+    for (var i = 0; i < selectionLayersNotSorted.length; i++) {
+        options += selectionLayersNotSorted[i];
+    }
```
Comment (rldhont) [inline lizmap/www/js/attributeTable.js]: Can you remove these 3 lines ? Selection can't be yet performed without attribute table configuration

**Comment by josemvm** [comment]
problems on loading related tables...

imagem

File: lizmap/www/js/attributeTable.js (hunk 1 above)
Comment (nboisteault) [reply lizmap/www/js/attributeTable.js]: @rldhont Do you still want those lines to be removed ?

Comment (rldhont) [reply lizmap/www/js/attributeTable.js]: @nboisteault I have commented these lines before merging.

**Comment by nboisteault** [comment]
@josemvm I can't reproduce your issue. Please open one with every steps please.
