### PR TITLE
[Tests] Enhance Drag'N Drop Edition form test to avoid regression

### LINKED ISSUE #2038: Add a test for the fix related to the PR #2013
The PR #2013 called "[Bugfix] Attribute edition sets to null unedited fields " has fixed a bug in 3.3.x and would be merged into release_3_4
We must add a test in 3.4 (or in master and cherry-pick into 3.4) for this fix

### PR DESCRIPTION
**Pull request by rldhont**
Fixes #2038

### CODE REVIEW

File: tests/qgis-projects/tests/dnd_form.sql [hunk 1]
```diff
@@ -65,7 +65,7 @@ ALTER TABLE ONLY tests_projects.dnd_form ALTER COLUMN id SET DEFAULT nextval('te
 --
 
 COPY tests_projects.dnd_form (id, field_in_dnd_form, field_not_in_dnd_form) FROM stdin;
-1	test	test
+1   test    test
```
Comment (mdouchin) [inline tests/qgis-projects/tests/dnd_form.sql:68]: There is an error here because of the replacement of TAB by spaces -> the SQL does not work

**Review by mdouchin — CHANGES_REQUESTED** [review]

File: tests/qgis-projects/tests/dnd_form.sql (hunk 1 above)
Comment (mdouchin) [reply tests/qgis-projects/tests/dnd_form.sql:68]: Do not forget to fix the other COPY statement

Comment (Gustry) [reply tests/qgis-projects/tests/dnd_form.sql:68]: > There is an error here because of the replacement of TAB by spaces -> the SQL does not work

So we should a test on the test ;-)

Comment (rldhont) [reply tests/qgis-projects/tests/dnd_form.sql]: Fix with `INSERT INTO ... VALUES`

File: tests/qgis-projects/tests/dnd_form.sql [hunk 2]
```diff
@@ -84,6 +83,73 @@ ALTER TABLE ONLY tests_projects.dnd_form
...
+
+ALTER TABLE ONLY tests_projects.dnd_form_geom ALTER COLUMN id SET DEFAULT nextval('tests_projects.dnd_form_geom_id_seq'::regclass);
+
+
+--
+-- Data for Name: dnd_form_geom; Type: TABLE DATA; Schema: tests_projects; Owner: lizmap
+--
+
+INSERT INTO tests_projects.dnd_form_geom (id, field_in_dnd_form, field_not_in_dnd_form, geom) VALUES
+    (1, 'test_geom, 'test_geom, '01010000206A080000BF599997AB39254116EA7038651D5841');
```
Comment (mdouchin) [inline tests/qgis-projects/tests/dnd_form.sql:134]: syntax error: quotes missing !

Comment (rldhont) [reply tests/qgis-projects/tests/dnd_form.sql]: Fixed thanks

**Review by drillinP — APPROVED** [review]

**Review by mdouchin — APPROVED** [review]
