### PR TITLE
[Bugfix] attribute table - doesn't export when a selection is active

### LINKED ISSUE #2770: attribute table -  doesn't export when a selection is active
### What is the bug?

as this comment https://github.com/3liz/lizmap-web-client/issues/2715#issuecomment-1031376587 by @rldhont 

_It is a regression in Lizmap, before 3.4.8 it was using EXP_FILTER and BBOX, now it uses FEATUREID instead of EXP_FILTER but FEATUREID and BBOX cannot be used in the same WFS request_

### Steps to reproduce the issue

make a selection in attribute and try to export to all formats

### Versions

 Lizmap Web Client : 3.4.9
 Lizmap plugin : 3.7.2
 QGIS Desktop : 3.16.16

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16.16

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

97

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rldhont**
fixes #2770

In the WFS OGC standard FEATUREID and BBOX parameters cannot be mutually set
but in Lizmap, the user can do a selection, based on featureid, and can request
a download, a WFS GetFeature request, based on this selection with a restriction
to map extent, sofeatureid and bbox parameter can be set mutually and featureid
parameter needs to be transform in an expression filter.

A parameter `FORCE_QGIS` has been introduced for GetFeature to compare lizmap
postgres GetFeature response and QGIS Server GetFeature response.

* Funded by 3Liz

### CODE REVIEW

File: lizmap/modules/lizmap/lib/Request/WFSRequest.php [hunk 1]
```diff
@@ -346,6 +348,115 @@ protected function process_getfeature()
...
+        // parameter needs to be transform in an expression filter.
+        // The transformation is only available if the QGIS layer has been set.
+        if ($this->param('featureid')
+            && $this->param('bbox')
+            && $this->qgisLayer) {
+            $provider = $this->qgisLayer->getProvider();
+
+            $typename = $this->requestedTypename();
+            $featureid = $this->param('featureid', '');
+
```
Comment (laurentj) [inline lizmap/modules/lizmap/lib/Request/WFSRequest.php:364]: I suggest to create a new method, `$expFilter = $this->getExpFilter($featureId, $typename)`, so getfeatureQgis will be more readable and not too long

File: lizmap/modules/lizmap/lib/Request/WFSRequest.php [hunk 2]
```diff
@@ -346,6 +348,115 @@ protected function process_getfeature()
...
+            $exp_filter = '';
+            if (($hasDoubleAtSign && $provider == 'postgres')
+                || !$hasDoubleAtSign) {
+                $fids = explode(',', $featureid);
+
+                // get primary keys values
+                $pks = array();
+                foreach ($fids as $fid) {
+                    $exp = explode('.', $fid);
+                    if (count($exp) == 2 and $exp[0] == $typename) {
```
Comment (mdouchin) [inline lizmap/modules/lizmap/lib/Request/WFSRequest.php:379]: We should control which data is given here, because it comes from a parameter, and could be used for SQL injections. QGIS Server probably does the job, but we could perhaps use a small regex to check if the values is simple enough ?

File: lizmap/modules/lizmap/lib/Request/WFSRequest.php (hunk 1 above)
Comment (laurentj) [reply lizmap/modules/lizmap/lib/Request/WFSRequest.php:364]: (and you could unit test this method)

**Comment by rldhont** [comment]
@laurentj I have created a specific method and added a unit test.

File: lizmap/modules/lizmap/lib/Request/WFSRequest.php (hunk 2 above)
Comment (rldhont) [reply lizmap/modules/lizmap/lib/Request/WFSRequest.php]: Wich regExp do you propose ?

**Comment by rldhont** [comment]
All cypress tests passed, to avoid error logs we need https://github.com/3liz/lizmap-web-client/pull/2956

File: lizmap/modules/lizmap/lib/Request/WFSRequest.php (hunk 2 above)
Comment (mdouchin) [reply lizmap/modules/lizmap/lib/Request/WFSRequest.php]: The method `validateFilter` seems to do the Job. Could you perhaps use it in this context ?

Comment (rldhont) [reply lizmap/modules/lizmap/lib/Request/WFSRequest.php]: `validateFilter is for postgres layer and update the expression to SQL, so I have introduced a `validateExpressionFilter` which is strict because of blockedWords. Key values cannot contain `;` or `--`.

**Review by mdouchin — APPROVED** [review]

**Review by laurentj — APPROVED** [review]
r+
