### PR TITLE
Fix export layer with accent

### LINKED ISSUE #3660: [Bug]: Export dropdown do not show in pop up if layer name in QGIS project has an accent
### What is the bug?

Scenario: QGIS project with some layer published as WFS and with the pop up dialog active. If permissions are granted is expected to see the export layer dropdown in the pop up dialog.

image

But...

if the layername in the QGIS project has an accent, i.e.

image

then it won't show. Actually I just noticed that if the layer name (in QGIS project) even start with an uppercase latter, also the export layer dropdown is a no show.

At some point I was even convinced that having two layers named in a similar way was enough to trigger this, but I struggled to replicate and after several hours of troubleshooting I'm fed with this as it seems a very finicky problem.

To note that this only affect the pop up dialog, as the export drodown shows as expected in the attribute table, even in the above cases.

### Steps to reproduce the issue

See above.

### Versions

QGIS LTR on Desktop and Server. Latest version of LMWC, Limap plugin and Lizmap Server plugin.

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28

### Operating system

Ubuntu 22.04, desktop and server

### Browsers

Firefox, Chrome

### Browsers version

Latest

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by nboisteault**
Fix #3660 but just for next Lizmap 3.7. @mdouchin @rldhont Any other idea to fix it for previous versions?

Funded by 3Liz

### CODE REVIEW

File: assets/src/legacy/switcher-layers-actions.js [hunk 1]
```diff
@@ -161,26 +161,12 @@ var lizLayerActionButtons = function() {
...
-                            showExport = true;
-                            continue;
-                        } else if (typeName == aName.split(' ').join('_') ) {
-                            showExport = true;
-                            continue;
-                        }
-                    }
-                }
-                if( showExport ) {
+                if( options != '' && lizMap.mainLizmap.initialConfig.attributeLayers.layerNames.includes(aName) ) {
```
Comment (rldhont) [inline assets/src/legacy/switcher-layers-actions.js:169]:
```suggestion
                if( options != '' && layerConfig.typename != undefined) {
```

**Review by rldhont — CHANGES_REQUESTED** [review]
