### PR TITLE
Fix Relation Reference Form control OrderByValue default value to true

### LINKED ISSUE #4419: [Bug]: values in relation tables are not sorted alphabetically
### What is the bug? (in English)

I have a table in postgresql which has several tables related to it. Each of these tables are lists and their values need to be sorted alphabetically to facilitate the data input. In QGIS if i edit the table and add a new records, then the values of the lists appear sorted. However, when i publish the project in lizmap and i add a new record, these values do not appear in alphabetical order anymore. 

### Steps to reproduce the issue

Upload a table from postgres with related tables (lists). 
Check that the related tables (lists) are mapped in the form (see screenshot below)
table_property
Then publish the project in lizmap.
In lizmap open the form and add the values. As showed below the values are not sorted
IMG20240508145557_cropped

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.6.9
* Lizmap plugin : 4.3.1
* QGIS Desktop : 3.34.6
* QGIS Server : 3.34.5
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22

### Browsers

Firefox, Chrome

### Browsers version

recent 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rldhont**
The orderByValue Relation reference property has been removed from XML since QGIS 3.32

Fixed #4419

Superseed #4764

### CODE REVIEW

File: lizmap/modules/lizmap/lib/Form/QgisForm.php [hunk 1]
```diff
@@ -1762,6 +1762,7 @@ protected function PerformWfsRequest($wfsRequest, $formControl, $referencedField
             }
 
             // orderByValue
+            // orderByValue has been removed from XML since QGIS 3.32
             if ($formControl->relationReferenceData['orderByValue']) {
```
Comment (Gustry) [inline lizmap/modules/lizmap/lib/Form/QgisForm.php:1766]:
```suggestion
            TODO Remove when QGIS 3.32 will be the minimum version for allowing a QGIS project
            if ($formControl->relationReferenceData['orderByValue']) {
```
I know, it doesn't exist yet. But something will arrive later about this I guess.

Comment (rldhont) [reply lizmap/modules/lizmap/lib/Form/QgisForm.php:1767]: Thanks @Gustry
