### PR TITLE
Refacto: avoid duplication of code in selectionTool

### LINKED ISSUE #5132: [Bug]: selection tool - buffer doesn´t work
### What is the bug? (in English)

the buffer doesn´t take into account the features of its ​​influence area

selectionTool

### Steps to reproduce the issue

try to select features using the buffer

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.4-pre.8084 - commit 4a1a1d5b6 https://github.com/3liz/lizmap-web-client/commit/4a1a1d5b6
* Lizmap plugin : 4.4.5
* QGIS Desktop : 3.34.12
* QGIS Server : 3.34.12
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.11.2
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of Lizmap Web Client modules :</summary>
<br/>
* multiauth : 1.2.2
</details>

<details>
<summary>List of safeguards :</summary>
<br/>
* Mode : normal<br/>
* Allow parent folder : no<br/>
* Prevent other drive : no<br/>
* Prevent PG service : no<br/>
* Prevent PG Auth DB : no<br/>
* Force PG user&pass : no<br/>
* Prevent ECW : no<br/>
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

132.0.2

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by nboisteault**
Fix #5132

Funded by 3Liz

### CODE REVIEW

File: assets/src/modules/SelectionTool.js [hunk 1]
```diff
@@ -498,74 +413,87 @@ export default class SelectionTool {
...
+                // Remove duplicates
+                featureIds = [...new Set(featureIds)];
+            } else if (this.newAddRemoveSelected === 'remove' ) { // Remove from selection
+                const toRemove = new Set(featureIds);
+                featureIds = lConfig['selectedFeatures'].filter( x => !toRemove.has(x) );
             }
-            lConfig['selectedFeatures'] = sfIds;
+
+            lConfig['selectedFeatures'] = featureIds;
             lizMap.events.triggerEvent("layerSelectionChanged",
```
Comment (rldhont) [inline assets/src/modules/SelectionTool.js:497]:
```suggestion
            this._lizmap3.events.triggerEvent("layerSelectionChanged",
```
Do not use  `lizMap`

**Review by rldhont — CHANGES_REQUESTED** [review]

**Comment by rldhont** [comment]
Thanks @nboisteault

**Comment by nboisteault** [comment]
Backport to release_3_8 manually made
