### PR TITLE
[Bugfix] Host in datasource between single quote

### LINKED ISSUE #2332: Bug with the connection to the database when editing on lizmap
### What is the bug?
A bug with the connection to the database when editing on lizmap.
when lizmap retrieves the datasource of the QGIS project the host is in quotes. However, lizmap did not plan to retrieve a host between quotes.

### Steps to reproduce the issue

1. Use a project QGIS without using service for connect to the database
2. Configure to lizmap
3. Click to edit a layer in lizmap
4. Editing loads continuously

 - Lizmap version: 3.4.*

### PR DESCRIPTION
**Pull request by rldhont**
In QGIS 3.16, the host in datasource can be wrote between single quote.

Fix #2332

### CODE REVIEW

File: tests/units/edition/qgisVectorLayerDatasourceTest.php [hunk 1]
```diff
@@ -29,6 +30,28 @@ function testPostgresqlDatasource() {
         $this->assertEquals('geom', $element->getDatasourceParameter('geocol'));
         $this->assertEquals('', $element->getDatasourceParameter('sql'));
 
+        // Host with '
+        $datasource = "dbname='test_dbname' host='test_host' port=5432 user='test_user' password='test_password' sslmode=disable key='id' srid=4326 type=Polygon checkPrimaryKeyUnicity='1' table=\"test_schema\".\"test_table\" (geom) sql=";
+
```
Comment (Gustry) [inline tests/units/edition/qgisVectorLayerDatasourceTest.php:35]:
```suggestion
$element = new qgisVectorLayerDatasource($provider, $datasource);
```

Comment (rldhont) [reply tests/units/edition/qgisVectorLayerDatasourceTest.php:35]: thanks, I forgot it

**Review by mdouchin — APPROVED** [review]

**Review by drillinP — APPROVED** [review]
